# Generated by Django 4.2.7 on 2023-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Nota', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
