# Generated by Django 4.2.7 on 2023-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Nota',
            field=models.SmallIntegerField(max_length=200),
        ),
    ]
