# Generated by Django 4.2.7 on 2023-12-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0002_alter_nota_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Nota',
            field=models.SmallIntegerField(),
        ),
    ]
