# Generated by Django 4.2.7 on 2023-12-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0004_alter_nota_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Nota',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
