# Generated by Django 4.2.7 on 2023-12-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0005_alter_nota_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
