# Generated by Django 4.2.7 on 2023-12-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0006_estadonota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='Fecha',
        ),
    ]
